### PR TITLE
Initialize session var in AdminController

### LINKED ISSUE #847: Set locales is error in Laravel5
I set 'locales' option in administrator.php
``
'locales' =>  array('en', 'zh-TW'),
``

When I click language ,it is error.

FatalErrorException in AdminController.php line 613:
Call to a member function put() on null

### PR DESCRIPTION
**Pull request by camiloclc**
Fix issues where the controller uses session. Closes #847.

### CODE REVIEW

**Comment by rich-choy** [comment]
Please merge this already

**Comment by komakino** [comment]
+1 Please merge

**Comment by davemathews** [comment]
will get this in this weekend.

**Comment by davemathews** [comment]
@camiloclc has to be pr'd to the dev branch not the master before we can accept it, please make the changes so we can get it in. But I am just going to add it in this weekend so you are good.

**Pull request closed without merging**
