### PR TITLE
Fix file download by including session as property in AdminController

### PR DESCRIPTION
**Pull request by javichito**

### CODE REVIEW

**Comment by rich-choy** [comment]
Bump. Please merge this!!!

**Comment by davemathews** [comment]
will do this weekend. #917

**Comment by davemathews** [comment]
@javichito has to be pr'd to the dev branch not the master before we can accept it, please make the changes so we can get it in. If you can't I will make the changes myself later tonight.

**Comment by davemathews** [comment]
I made the change maually

**Pull request closed without merging**
