### PR TITLE
Update settings.php for `Request::url()` instead of using `url()`

### PR DESCRIPTION
**Pull request by namreg**
related issue https://github.com/FrozenNode/Laravel-Administrator/issues/972

### CODE REVIEW

**Comment by mrchimp** [comment]
Any chance of getting this merged?

**Comment by davemathews** [comment]
will get this asap

**Comment by lazyguru** [comment]
Any update here? I'm having the same issue

**Comment by kinow** [comment]
Tested locally, change in PR fixes the issue in my environment:

```
laravel/framework                     v5.2.27 The Laravel Framework.
frozennode/administrator              v5.0.11 A database interface package for Laravel
```

**Comment by metal3d** [comment]
Same, tested and it work if I change myself in settings.php
Seems to be urgent, isn't it ?

**Comment by timbroder** [comment]
Can confirm this fixes it for me as well

**Comment by nata-sch-21** [comment]
I update settings.php. thanks for the advice. all works now

**Comment by warksit** [comment]
This also working for me, please can this be merged?

**Comment by mrchimp** [comment]
> will get this asap

ASAP is almost six months for a single line with no side effects?

**Comment by lazyguru** [comment]
>> will get this asap

> ASAP is almost six months for a single line with no side effects?


Let's all remember this is an open source project.  I'm sure @davemathews is working on it in his spare time.  We all have lives and work beyond what we are committing to open source projects.  If he isn't as attentive as you would like, you can always fork the repo and maintain your own copy.  If you want to try encouraging him to spend more time on this, perhaps suggesting how much you would be willing to pay for his time might help?

**Comment by mrchimp** [comment]
Well I feel like a bit of an asshole now but thanks Dave!

**Comment by zhafariirsyad** [comment]
Excuse me, where is the location of settings.php?

**Pull request merged**
