### PR TITLE
Autocomplete working with default value

### PR DESCRIPTION
**Pull request by RemiCollin**

### CODE REVIEW

**Comment by Mythli** [comment]
Hello RemiCollin, I will investigate your fix. So far it is working without any further issues. Send me your paypal name if you want your reward.

**Comment by RemiCollin** [comment]
Just sent you a mail.

**Comment by sparkeleven** [comment]
Defaulted values for non-autocomplete relationship fields are also not working. Can you devise a similar fix?

**Comment by RemiCollin** [comment]
The fix pulls default relationship value autocomplete or not to the client side. I remember testing it with non-autocomplete fields and it did work.

**Comment by sparkeleven** [comment]
Ok, yes it works. I was hoping it might also fix the issue where the actual current value of a relationship is not being chosen from the list of available values and it only ever displays the placeholder "Select some options". This pull request should be merged anyway, collaborators!

**Comment by davemathews** [comment]
@RemiCollin I am going to do some testing and hopefully get this in today if it all works out.

**Pull request merged**
